#!/bin/sh
set -e
set -x

rm -f /tmp/cif_httpd.pid
rm -f /tmp/cif_router.pid

# Pull in ENV vars for cif setup
#/cif-helpers/setup-cif-env.py

# Generate required tokens if they don't exist
#/cif-helpers/elasticsearch-token-setup.sh

# cp /var/lib/cif/.cif.yml /home/cif/
# cp /var/lib/cif/csirtg-smrt.yml /etc/cif/
# cp /var/lib/cif/cif-router.yml /etc/cif/

export CIF_RUNTIME_PATH=/var/lib/cif
export CIF_DATA_PATH=/var/lib/cif
export CIF_ROUTER_TRACE=1
export CIF_ROUTER_PIDFILE=/tmp/cif_router.pid
export CIF_HUNTER_ADVANCED=1

# TODO: Replace this with a script of some sort, this is aweful
if [[ ! -z "${CIF_HUNTER_WHITELIST}" ]]; then
    cd /inactive_hunters
    for HUNTER in $(echo $CIF_HUNTER_WHITELIST | sed "s/,/ /g"); do
        echo "Enabling hunter ${HUNTER}"
        mv ${HUNTER} /usr/local/lib/python3.6/site-packages/cif-${CIF_VERSION}-py3.6.egg/cif/hunter/
    done
fi

cat << EOF > /etc/cif/cif-router.yml
---
hunter_token: ${CIF_TOKEN_HUNTER}

EOF

until curl -s "http://${CIF_STORE_NODES}/_cluster/health"; do
    echo "Waiting for ${CIF_STORE_NODES} to be up"
    sleep 5
done

cif-router --config=/etc/cif/cif-router.yml \
    --hunter-threads 2 \
    --gatherer-threads 2
