---

version: '3'
services:
  cif-http:
    build: .
    restart: on-failure
    ports:
      - 5000:5000
    environment:
      CIF_TOKEN_HUNTER: "foo"
      CIF_TOKEN_ADMIN: "bar"
      CIF_TOKEN_SMRT: "baz"
      CIF_TOKEN_HTTP: "quux"
    volumes:
      - cif-config:/etc/cif
      - cif-logs:/var/log/cif
      - cif-db:/var/lib/cif
      - geoip:/usr/share/GeoIP
  cif-router:
    build: .
    restart: on-failure
    environment:
      CIF_STORE_STORE: "elasticsearch"
      CIF_STORE_NODES: "elasticsearch:9200"
      CIF_TOKEN_HUNTER: "foo"
      CIF_TOKEN_ADMIN: "bar"
      CIF_TOKEN_SMRT: "baz"
      CIF_TOKEN_HTTP: "quux"
      CIF_HUNTER_WHITELIST: "logging_hunter.py"
    entrypoint: /cif-helpers/entrypoint-router
    volumes:
      - cif-config:/etc/cif
      - cif-logs:/var/log/cif
      - cif-db:/var/lib/cif
      - geoip:/usr/share/GeoIP
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.4.3
    container_name: elasticsearch_mini
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9200"]
        interval: 30s
        timeout: 10s
        retries: 5
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  cif-config:
  cif-logs:
  cif-db:
  esdata:
  geoip:
  esdata:
